services:
  - type: web
    name: xlense-backend
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    env: node

  - type: static
    name: xlense-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
